# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Zendai Kashino"
tagline:          'ikura wa ikura?'
description:      'Super cool grad student'
url:              http://zendkash.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

