# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Zendai Kashino"
tagline:          'ikura wa ikura?'
description:      'Super cool grad student'
url:              "/"
#baseurl:          /
baseurl:          "http://zendkash.github.io/"

defaults:
    -
     scope:
         path: ""
     values:
         author: me
         layout: default
         lang: en
         base-url: "/"
    -
     scope:
         path: jp
     values:
         lang: jp
         base-url: "/jp/"
t:
    title:
        en: "Zendai Kashino"
        jp: "ゼンダイ"
    description:
        en: "Super cool grad student"
        jp: "Suppura kakkoi gakuinsei"
    langchange:
        en: "English"
        jp: "日本語"
