# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Zenpoo"
tagline:          'To infinity and beyond'
description:      'Description'
url:              http://zendkash.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

