# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Zendai Kashino"
tagline:          '柏野　善大'
description:      'Ph.D. Candidate at UofT'
url:              "/"
#baseurl:          /
baseurl:          "https://zendkash.github.io/"

defaults:
    -
     scope:
         path: ""
     values:
         author: me
         layout: default
         lang: en
         base-url: "/"
    -
     scope:
         path: jp
     values:
         lang: jp
         base-url: "/jp/"
t:
    title:
        en: "Zendai Kashino"
        jp: "柏野　善大"
    description:
        en: "Ph.D. Candidate at UofT"
        jp: "トロント大学博士候補"
    langchange:
        en: "English"
        jp: "日本語"
