# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Zendai Kashino"
tagline:          'ikura wa ikura?'
description:      'Super cool grad student'
url:              http://zendkash.github.io
baseurl:          /

defaults:
    -
     scope:
         path: ""
     values:
         author: "me"
         layout: default
         lang: en
         base-url: "/"
    -
     scope:
         path: jp
     values:
         lang: jp
         base-url: "/jp/"
